# Generated by Django 4.2.3 on 2024-02-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(default="01/02/24"),
        ),
    ]
