# Generated by Django 4.2.3 on 2024-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(default="2024/02/24"),
        ),
    ]
